#!/usr/bin/env python3
"""
Comprehensive IRCoT Pipeline Test Script

This script provides a comprehensive test of the IRCoT (Interleaving Retrieval with 
Chain-of-Thought) implementation, demonstrating its capabilities on multiple types
of questions.

Test Coverage:
- Multi-hop reasoning questions (from HotpotQA demonstrations)
- Knowledge-intensive factual questions  
- Questions requiring synthesis across multiple sources
- Edge cases where knowledge may not be in the corpus

Components Tested:
- FAISS-based dense retrieval with Wikipedia corpus
- Mistral LLM for reasoning step generation
- Few-shot prompting with official IRCoT demonstrations
- Complete iterative retrieval loop
- Final answer generation and formatting

Output Format:
For each test question, the script shows:
1. The question being asked
2. Chain-of-thought reasoning steps generated by IRCoT
3. Retrieved paragraphs that informed the reasoning
4. Final synthesized answer

This provides visibility into how IRCoT works internally and demonstrates
the quality of reasoning and retrieval for different question types.

Usage:
    uv run python scripts/test_ircot_pipeline.py

Requirements:
- FAISS index files in notebooks/ directory
- MISTRAL_API_KEY environment variable set
- All IRCoT dependencies installed via uv
"""

import sys
from pathlib import Path

# Add project root to Python path
PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from src.reasoning.ircot import (
    IRCoTConfig,
    IRCoTRetriever,
    MistralLLMClient,
    QAReader,
    load_default_hotpot_demos,
    load_faiss_retriever_from_notebooks,
)
import os


def main():
    """Run the IRCoT pipeline test."""
    print("🚀 IRCoT Pipeline Test")
    print("=" * 50)
    
    # Load configuration and demos
    config = IRCoTConfig()
    demos = load_default_hotpot_demos(max_examples=config.max_demos)
    print(f"✅ Loaded {len(demos)} few-shot demonstrations")
    
    # Initialize FAISS retriever
    notebooks_dir = PROJECT_ROOT / "notebooks"
    retriever = load_faiss_retriever_from_notebooks(str(notebooks_dir))
    print("✅ FAISS retriever loaded successfully")
    
    # Initialize Mistral LLM
    llm = MistralLLMClient()
    print("✅ MistralLLMClient initialized")
    
    # Initialize IRCoT components
    ircot = IRCoTRetriever(
        retriever=retriever,
        llm=llm,
        demos=demos,
        config=config,
    )
    
    reader = QAReader(
        llm=llm,
        demos=demos,
        config=config,
    )
    
    # Test questions
    test_questions = [
        demos[0].question if demos else "What is the capital of France?",
        "Who invented the telephone?",
        "What is the largest planet in our solar system?",
    ]
    
    for i, question in enumerate(test_questions, 1):
        print(f"\n{'='*50}")
        print(f"🔍 Test {i}: {question}")
        print('='*50)
        
        # Run IRCoT
        result = ircot.run(question)
        
        print(f"\n📝 Chain-of-Thought Steps ({len(result.cot_steps)}):")
        for j, step in enumerate(result.cot_steps, 1):
            print(f"  {j}. {step}")
        
        print(f"\n📚 Retrieved Paragraphs ({len(result.retrieved_paragraphs)}):")
        for j, para in enumerate(result.retrieved_paragraphs[:3], 1):  # Show top 3
            print(f"  {j}. {para.title}")
            print(f"     {para.text[:80]}...")
        
        # Generate answer
        qa_result = reader.answer(question, result.retrieved_paragraphs)
        
        print(f"\n💡 Final Answer:")
        print(f"  {qa_result.answer}")
        
        if i < len(test_questions):  # Don't print separator after last question
            print(f"\n{'─'*50}")
    
    print(f"\n🎉 IRCoT Pipeline Test Complete!")
    print("=" * 50)


if __name__ == "__main__":
    main()
